import { useCallback, useEffect, useRef, useState } from 'react';
import { fetchWithAuth } from '../../api/fetchWithAuth.js';
import origin from '../../api/apiOrigin.js';
import styles from '../../pages/dashboard/DashboardPages.module.css';
import settingsStyles from '../../pages/dashboard/SettingsPage.module.css';

export function ChartNarration({ summary, chartData, startDate, endDate }) {
  const [narration, setNarration] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [hasGenerated, setHasGenerated] = useState(false);
  const inFlightRequestKeyRef = useRef(null);

  const handleExplain = useCallback(async () => {
    if (
      summary == null ||
      chartData == null ||
      !chartData.records ||
      chartData.records.length === 0
    ) {
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const requestBody = {
        startDate: startDate ?? null,
        endDate: endDate ?? null,
        totalRevenue: summary.totalRevenue,
        totalExpenses: summary.totalExpenses,
        totalGrossProfit: summary.totalGrossProfit,
        avgProfitMargin: summary.avgProfitMargin,
        monthlyBreakdown: chartData.records.map((r) => ({
          period: r.period,
          revenue: r.total_revenue,
          expenses: r.total_expenses,
          grossProfit: r.gross_profit,
        })),
      };
      const requestKey = JSON.stringify(requestBody);
      if (inFlightRequestKeyRef.current === requestKey) {
        return;
      }
      inFlightRequestKeyRef.current = requestKey;

      const res = await fetchWithAuth(`${origin}/api/narrate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
      });

      const json = await res.json();

      if (res.ok) {
        setNarration(json.data.narration);
        setHasGenerated(true);
      } else {
        setNarration(null);
        setError(
          json.message || 'Failed to generate summary. Please try again.'
        );
        setHasGenerated(true);
      }
    } catch {
      setNarration(null);
      setError('Failed to generate summary. Please try again.');
      setHasGenerated(true);
    } finally {
      inFlightRequestKeyRef.current = null;
      setLoading(false);
    }
  }, [summary, chartData, startDate, endDate]);

  useEffect(() => {
    if (!hasGenerated) return;
    setNarration(null);
    setError(null);
    setHasGenerated(false);
  }, [startDate, endDate]);

  if (
    summary == null ||
    chartData == null ||
    chartData.records == null
  ) {
    return null;
  }

  return (
    <div className={styles.narrateEmbed}>
      <div className={styles.narrateEmbedStack}>
        <h3 className={styles.narrateEmbedTitle}>AI Chart Summary</h3>
        {loading && (
          <p className={styles.narrateMuted}>
            Analysing your financial data…
          </p>
        )}

        {!loading && error && (
          <>
            <div
              className={`${settingsStyles.feedback} ${settingsStyles.feedbackError} ${settingsStyles.twoFactorEmbeddedFeedback}`}
              role="alert"
            >
              {error}
            </div>
            <button
              type="button"
              onClick={handleExplain}
              disabled={loading}
              className={`${settingsStyles.actionBtn} ${settingsStyles.dangerBtn}`}
            >
              Regenerate summary
            </button>
          </>
        )}

        {!loading && !error && !narration && (
          <div className={styles.narrateOutlineBtnWrap}>
            <button
              type="button"
              onClick={handleExplain}
              disabled={loading}
              className={`${styles.forecastDownloadBtn} ${styles.forecastDownloadBtnSubtle}`}
            >
              Generate chart summary
            </button>
          </div>
        )}

        {!loading && !error && narration && (
          <>
            <p className={styles.narrateText}>{narration}</p>
            <p className={styles.narrateDisclaimer}>
              This summary is generated by AI and reflects
              historical data only. It is not financial advice.
            </p>
            <div className={styles.forecastDownloadWrap}>
              <button
                type="button"
                onClick={handleExplain}
                disabled={loading}
                className={`${settingsStyles.actionBtn} ${settingsStyles.dangerBtn}`}
              >
                Regenerate summary
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
